In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly as py
import plotly.express as px
py.offline.init_notebook_mode(connected=True)

In [2]:
df=pd.read_csv("cars.csv")
df.sample(10)

,brand,km_driven,fuel,owner,selling_price
4947,Ford,77524,Diesel,First Owner,875000
5189,Toyota,440000,Diesel,Second Owner,750000
1057,BMW,56000,Diesel,First Owner,3750000
7819,Mahindra,60000,Diesel,Second Owner,700000
4400,Volkswagen,5000,Petrol,First Owner,808000
3772,Honda,93500,Petrol,Third Owner,350000
3281,Toyota,40000,Petrol,Third Owner,350000
1263,Hyundai,100000,Petrol,Fourth & Above Owner,81000
4892,Chevrolet,100000,Petrol,Third Owner,65000
1532,Tata,70000,Diesel,First Owner,310000


In [3]:
df.shape

(8128, 5)

In [4]:
df['brand'].unique()

array(['Maruti', 'Skoda', 'Honda', 'Hyundai', 'Toyota', 'Ford', 'Renault',
       'Mahindra', 'Tata', 'Chevrolet', 'Fiat', 'Datsun', 'Jeep',
       'Mercedes-Benz', 'Mitsubishi', 'Audi', 'Volkswagen', 'BMW',
       'Nissan', 'Lexus', 'Jaguar', 'Land', 'MG', 'Volvo', 'Daewoo',
       'Kia', 'Force', 'Ambassador', 'Ashok', 'Isuzu', 'Opel', 'Peugeot'],
      dtype=object)

In [5]:
df['brand'].nunique()

32

In [6]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [7]:
df['fuel'].unique()

array(['Diesel', 'Petrol', 'LPG', 'CNG'], dtype=object)

In [8]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [9]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

One hot Encoding Using Pandas

In [10]:
df.head()

,brand,km_driven,fuel,owner,selling_price
0,Maruti,145500,Diesel,First Owner,450000
1,Skoda,120000,Diesel,Second Owner,370000
2,Honda,140000,Petrol,Third Owner,158000
3,Hyundai,127000,Diesel,First Owner,225000
4,Maruti,120000,Petrol,First Owner,130000


In [12]:
pd.get_dummies(df,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False


K-1 One Hot Encoding

In [13]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False


One Hot Encoding using Sklearn

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,0:4],df.iloc[:,-1],
                                               test_size=0.2,
                                               random_state=100)

In [15]:
x_train.head()

,brand,km_driven,fuel,owner
2348,Hyundai,26000,Petrol,First Owner
5852,Maruti,50000,Diesel,First Owner
4897,Skoda,55885,Petrol,First Owner
3816,Maruti,60000,Diesel,First Owner
5725,Honda,140000,Diesel,First Owner


In [17]:
x_train['fuel'].value_counts(),x_train['owner'].value_counts()

(fuel
 Diesel    3505
 Petrol    2924
 CNG         42
 LPG         31
 Name: count, dtype: int64,
 owner
 First Owner             4228
 Second Owner            1690
 Third Owner              443
 Fourth & Above Owner     137
 Test Drive Car             4
 Name: count, dtype: int64)

In [18]:
from sklearn.preprocessing import OneHotEncoder

In [19]:
ohe=OneHotEncoder(drop='first')#sparse =false so we dont have to use .toarray()

In [20]:
x_train_new=ohe.fit_transform(x_train[['fuel','owner']]).toarray()
x_train_new

array([[0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       [0., 0., 1., ..., 0., 0., 0.]])

In [21]:
x_train_new.shape

(6502, 7)

In [22]:
x_test_new=ohe.transform(x_test[['fuel','owner']]).toarray()
x_test_new

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]])

In [23]:
x_test_new.shape

(1626, 7)

In [24]:
x_train[['brand','km_driven']].values

array([['Hyundai', 26000],
       ['Maruti', 50000],
       ['Skoda', 55885],
       ...,
       ['Maruti', 35000],
       ['Tata', 110000],
       ['Hyundai', 70000]], dtype=object)

In [26]:
np.hstack((x_train[['brand', 'km_driven']].values, x_train_new))

array([['Hyundai', 26000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Maruti', 50000, 1.0, ..., 0.0, 0.0, 0.0],
       ['Skoda', 55885, 0.0, ..., 0.0, 0.0, 0.0],
       ...,
       ['Maruti', 35000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Tata', 110000, 1.0, ..., 0.0, 0.0, 1.0],
       ['Hyundai', 70000, 0.0, ..., 0.0, 0.0, 0.0]], dtype=object)

In [ ]:
np.hstack((x_train[['brand', 'km_driven']].values, x_train_new)).shape

(6502, 9)

In [43]:
x_train_new.shape

(6502, 7)

In [47]:
counts=df['brand'].value_counts()
counts

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [49]:
threshold=100
counts[counts<=threshold].index

Index(['Nissan', 'Jaguar', 'Volvo', 'Datsun', 'Mercedes-Benz', 'Fiat', 'Audi',
       'Lexus', 'Jeep', 'Mitsubishi', 'Force', 'Land', 'Isuzu', 'Kia',
       'Ambassador', 'Daewoo', 'MG', 'Ashok', 'Opel', 'Peugeot'],
      dtype='object', name='brand')

In [50]:
repl=counts[counts<=threshold].index

In [51]:
pd.get_dummies(df['brand'].replace(repl,'uncommon'))

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
0,False,False,False,False,False,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,True,False,False,False,False
2,False,False,False,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,False,False,False,False,True,False,False,False,False,False,False,False,False
8124,False,False,False,False,True,False,False,False,False,False,False,False,False
8125,False,False,False,False,False,False,True,False,False,False,False,False,False
8126,False,False,False,False,False,False,False,False,False,True,False,False,False


Column Transformer

In [52]:
import numpy as np
import pandas as pd

In [53]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [54]:
df=pd.read_csv("covid_toy.csv")
df.head()

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,Mild,Kolkata,No
1,27,Male,100.0,Mild,Delhi,Yes
2,42,Male,101.0,Mild,Delhi,No
3,31,Female,98.0,Mild,Kolkata,No
4,65,Female,101.0,Mild,Mumbai,No


In [57]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [58]:
pd.crosstab(df['gender'],df['city'])

city,Bangalore,Delhi,Kolkata,Mumbai
gender,,,,
Female,16,13,19,11
Male,14,9,13,5


In [61]:
pd.pivot_table(df,values='age',columns='gender',index='city')

gender,Female,Male
city,,
Bangalore,41.375000,45.428571
Delhi,56.384615,37.333333
Kolkata,35.736842,50.538462
Mumbai,46.636364,41.200000


In [62]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [63]:
df.sample(5)

,age,gender,fever,cough,city,has_covid
95,12,Female,104.0,Mild,Bangalore,No
28,16,Male,104.0,Mild,Kolkata,No
12,25,Female,99.0,Strong,Kolkata,No
87,47,Male,101.0,Strong,Bangalore,No
58,23,Male,98.0,Strong,Mumbai,Yes


In [65]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.drop(columns='has_covid'),df['has_covid'],
                                               test_size=0.2)

In [66]:
x_train

,age,gender,fever,cough,city
46,19,Female,101.0,Mild,Mumbai
98,5,Female,98.0,Strong,Mumbai
12,25,Female,99.0,Strong,Kolkata
5,84,Female,NaN,Mild,Bangalore
13,64,Male,102.0,Mild,Bangalore
...,...,...,...,...,...
81,65,Male,99.0,Mild,Delhi
25,23,Male,NaN,Mild,Mumbai
27,33,Female,102.0,Strong,Delhi
67,65,Male,99.0,Mild,Bangalore


Aam Zindagi

In [69]:
#adding simple impute to fever col
si=SimpleImputer()
x_train_fever=si.fit_transform(x_train[['fever']])

x_test_fever=si.transform(x_test[['fever']])
x_train_fever

array([[101.        ],
       [ 98.        ],
       [ 99.        ],
       [100.81944444],
       [102.        ],
       [102.        ],
       [ 98.        ],
       [103.        ],
       [100.        ],
       [101.        ],
       [103.        ],
       [101.        ],
       [104.        ],
       [102.        ],
       [ 98.        ],
       [ 98.        ],
       [104.        ],
       [102.        ],
       [ 98.        ],
       [101.        ],
       [100.        ],
       [ 98.        ],
       [102.        ],
       [ 98.        ],
       [100.81944444],
       [ 99.        ],
       [104.        ],
       [100.        ],
       [100.        ],
       [101.        ],
       [ 98.        ],
       [ 98.        ],
       [101.        ],
       [101.        ],
       [103.        ],
       [104.        ],
       [100.81944444],
       [101.        ],
       [103.        ],
       [100.        ],
       [102.        ],
       [104.        ],
       [100.81944444],
       [101

In [70]:
x_train_fever.shape

(80, 1)

In [71]:
#adding ordinal encoding-->cough
oe=OrdinalEncoder(categories=[['Mild','Strong']])
x_train_cough=oe.fit_transform(x_train[['cough']])
x_test_cough=oe.transform(x_test[['cough']])
x_train_cough.shape

(80, 1)

In [77]:
#one Hot encoding
ohe=OneHotEncoder(drop='first',sparse_output=False)
x_train_gender_city=ohe.fit_transform(x_train[['gender','city']])
x_test_gender_city=ohe.transform(x_test[['gender','city']])
x_train_gender_city

array([[0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],


In [78]:
x_train_gender_city.shape

(80, 4)

In [82]:
x_train_age=x_train.drop(columns=['gender','fever','cough','city']).values
x_test_age=x_test.drop(columns=['gender','fever','cough','city']).values
x_train_age

array([[19],
       [ 5],
       [25],
       [84],
       [64],
       [ 5],
       [73],
       [69],
       [27],
       [20],
       [73],
       [65],
       [56],
       [49],
       [40],
       [80],
       [ 6],
       [20],
       [64],
       [34],
       [ 5],
       [24],
       [82],
       [10],
       [79],
       [66],
       [51],
       [47],
       [10],
       [83],
       [34],
       [26],
       [19],
       [ 8],
       [46],
       [25],
       [42],
       [15],
       [70],
       [80],
       [24],
       [42],
       [82],
       [47],
       [71],
       [74],
       [14],
       [51],
       [38],
       [27],
       [81],
       [12],
       [27],
       [12],
       [69],
       [75],
       [34],
       [48],
       [83],
       [22],
       [31],
       [75],
       [65],
       [54],
       [18],
       [49],
       [11],
       [23],
       [82],
       [50],
       [16],
       [55],
       [11],
       [83],
       [14],
       [65],
       [23],

In [83]:
x_train_age.shape

(80, 1)

In [91]:
x_train_transform=np.concatenate((x_train_age,x_train_fever,x_train_gender_city
                            ,x_train_cough),axis=1)
x_test_transform=np.concatenate((x_test_age,x_test_fever,x_test_gender_city
                            ,x_test_cough),axis=1)
x_train_transform

array([[ 19.        , 101.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [  5.        ,  98.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   1.        ],
       [ 25.        ,  99.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 84.        , 100.81944444,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 64.        , 102.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [  5.        , 102.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 73.        ,  98.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 69.        , 103.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 27.        , 100.        ,   1.        ,   1.        ,
          0.    

In [92]:
x_train_transform.shape

(80, 7)

Mentos Zindagi

In [93]:
from sklearn.compose import ColumnTransformer

In [94]:
df.head()

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,Mild,Kolkata,No
1,27,Male,100.0,Mild,Delhi,Yes
2,42,Male,101.0,Mild,Delhi,No
3,31,Female,98.0,Mild,Kolkata,No
4,65,Female,101.0,Mild,Mumbai,No


In [95]:
trasformer=ColumnTransformer(transformers=[
                                            ('tnf1',SimpleImputer(),['fever']),
                                            ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
                                            ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city']),
                                            ],remainder='passthrough')

In [96]:
trasformer.fit_transform(x_train)

array([[101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  19.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   5.        ],
       [ 99.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  25.        ],
       [100.81944444,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  84.        ],
       [102.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  64.        ],
       [102.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   5.        ],
       [ 98.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  73.        ],
       [103.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  69.        ],
       [100.        ,   0.        ,   1.        ,   1.        ,
          0.    

In [100]:
trasformer.fit_transform(x_train).shape

(80, 7)

In [101]:
trasformer.transform(x_test).shape

(20, 7)