In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly as py
import plotly.express as px
py.offline.init_notebook_mode(connected=True)

Ordinal Encoding (Ordinal Categorical data)
One Hot Encoding (Nominal Categorical data)
Label Encoding

ordinal encoding (uses for only for training cols (input) which are ordimal cat)
label encoding  (used fo r target col which is orsinal cat)

In [2]:
df=pd.read_csv('customer.csv')
df.sample(5)

,age,gender,review,education,purchased
2,70,Female,Good,PG,No
15,75,Male,Poor,UG,No
10,98,Female,Good,UG,Yes
38,45,Female,Good,School,No
34,86,Male,Average,School,No


In [3]:
df.isna().sum()

age          0
gender       0
review       0
education    0
purchased    0
dtype: int64

In [4]:
df=df.iloc[:,2:]

In [5]:
df.head()

,review,education,purchased
0,Average,School,No
1,Poor,UG,No
2,Good,PG,No
3,Good,PG,No
4,Average,UG,No


In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,0:2],df.iloc[:,-1],
                                               test_size=0.2,
                                               random_state=0)
x_train.head()

,review,education
33,Good,PG
35,Poor,School
26,Poor,PG
34,Average,School
18,Good,School


In [7]:
from sklearn.preprocessing import OrdinalEncoder

In [8]:
oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [9]:
oe.fit_transform(x_train)

array([[2., 2.],
       [0., 0.],
       [0., 2.],
       [1., 0.],
       [2., 0.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [2., 2.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [1., 0.],
       [2., 0.],
       [1., 0.],
       [0., 1.],
       [2., 0.],
       [2., 1.],
       [0., 1.],
       [0., 0.],
       [1., 2.],
       [1., 2.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [1., 2.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [2., 2.],
       [1., 1.]])

In [40]:
oe.transform(x_test)

array([[0., 0.],
       [2., 1.],
       [2., 1.],
       [2., 2.],
       [2., 2.],
       [0., 2.],
       [2., 0.],
       [0., 0.],
       [0., 2.],
       [1., 1.]])

In [41]:
oe.categories

[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']]

In [42]:
from sklearn.preprocessing import LabelEncoder

In [43]:
le=LabelEncoder()

In [44]:
le.fit_transform(y_train)

array([1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0])

In [45]:
le.transform(y_test)

array([0, 1, 1, 1, 0, 0, 0, 1, 1, 0])