In [2]:
import numpy as np

In [3]:
np.array([1,3,4,5,6,6])

array([1, 3, 4, 5, 6, 6])

In [5]:
type(np.array([1,3,4,5,6,6,"sudh",True]))

numpy.ndarray

In [6]:
np.array([1,3,4,5,6,6,"sudh","yeu",True])

array(['1', '3', '4', '5', '6', '6', 'sudh', 'yeu', 'True'], dtype='<U11')

In [8]:
np.array([1,2,3.1,34])#upcasting

array([ 1. ,  2. ,  3.1, 34. ])

In [11]:
np.array([[1,2,"sud"],12,34.0,"guy"])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [12]:
np.array([[1,2,"sud"],[12,34.0,"guy"]])

array([['1', '2', 'sud'],
       ['12', '34.0', 'guy']], dtype='<U32')

In [14]:
np.array([[1,2,3],[4,5,6],[8,9,7]])

array([[1, 2, 3],
       [4, 5, 6],
       [8, 9, 7]])

In [15]:
np.array([1,2,3],ndmin=3)

array([[[1, 2, 3]]])

In [16]:
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [17]:
np.array([(1,2),(3,4)])

array([[1, 2],
       [3, 4]])

In [ ]:
#29:06

In [2]:
import numpy as np

In [34]:
arr=np.array([(1,2),(3,4)],dtype=[('a','<i2'),('b','<i8')])

In [4]:
arr

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [5]:
type(arr[0][0])

numpy.int16

In [6]:
type(arr[0][1])

numpy.int64

In [36]:
arr=np.array([[1,3,],[2,4]])
arr

array([[1, 3],
       [2, 4]])

In [12]:
arr[0]

array([1, 3])

In [15]:
type(arr[0])

numpy.ndarray

In [23]:
mat=np.mat(arr)

In [19]:
l=[3,4,5,6,78,8]

In [20]:
np.array(l)

array([ 3,  4,  5,  6, 78,  8])

In [21]:
np.asarray(l)

array([ 3,  4,  5,  6, 78,  8])

In [22]:
np.asanyarray(l)

array([ 3,  4,  5,  6, 78,  8])

In [24]:
np.asanyarray(mat)

matrix([[1, 3],
        [2, 4]])

In [25]:
np.asarray(mat)

array([[1, 3],
       [2, 4]])

In [28]:
issubclass(np.matrix,np.ndarray)

True

Deep copy and Shallow copy

Array is mutable

In [37]:
a=arr
arr

array([[1, 3],
       [2, 4]])

In [38]:
a[0][1]

3

In [39]:
a[0][1]=100

In [40]:
arr[0][1]

100

In [41]:
arr #deep copy

array([[  1, 100],
       [  2,   4]])

In [45]:
#shallow copy
a=arr.copy()
arr

array([[  1, 100],
       [  2,   4]])

In [46]:
a[0][1]

100

In [48]:
a[0][1]=284919
a

array([[     1, 284919],
       [     2,      4]])

In [50]:
arr # shallow copy

array([[  1, 100],
       [  2,   4]])

In [51]:
a=arr
b=np.copy(arr) #using numpy

In [52]:
a

array([[  1, 100],
       [  2,   4]])

In [53]:
b[0][1]=333333334
b

array([[        1, 333333334],
       [        2,         4]])

In [54]:
a

array([[  1, 100],
       [  2,   4]])

In [57]:
a[0:10890]

array([[  1, 100],
       [  2,   4]])

In [58]:
a[-1:]

array([[2, 4]])

In [59]:
a[-1::-1]

array([[  2,   4],
       [  1, 100]])

In [61]:
a

array([[  1, 100],
       [  2,   4]])

In [63]:
np.fromfunction(lambda i,j:i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [64]:
type(np.fromfunction(lambda i,j:i==j,(4,4)))

numpy.ndarray

In [66]:
np.fromfunction(lambda i,j:i**j,(4,4))

array([[ 1.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  2.,  4.,  8.],
       [ 1.,  3.,  9., 27.]])

In [3]:
np.fromfunction(lambda i,j:i*j,(9,2))

array([[0., 0.],
       [0., 1.],
       [0., 2.],
       [0., 3.],
       [0., 4.],
       [0., 5.],
       [0., 6.],
       [0., 7.],
       [0., 8.]])

In [5]:
np.fromfunction(lambda i,j:i/j*i,(4,4))

C:\Users\niraj\AppData\Local\Temp\ipykernel_57536\873926644.py:1: RuntimeWarning: divide by zero encountered in divide
  np.fromfunction(lambda i,j:i/j*i,(4,4))
C:\Users\niraj\AppData\Local\Temp\ipykernel_57536\873926644.py:1: RuntimeWarning: invalid value encountered in divide
  np.fromfunction(lambda i,j:i/j*i,(4,4))


array([[       nan, 0.        , 0.        , 0.        ],
       [       inf, 1.        , 0.5       , 0.33333333],
       [       inf, 4.        , 2.        , 1.33333333],
       [       inf, 9.        , 4.5       , 3.        ]])

In [6]:
[i*i for i in range(10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [11]:
gen=(i*i for i in range(10))#generator

In [8]:
def test(x):
    yield x

In [9]:
test(5)

<generator object test at 0x000001AFBD5E5B40>

In [18]:
gen

<generator object <genexpr> at 0x000001AFBD6557D0>

In [14]:
np.fromiter(gen,dtype=int)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [15]:
np.fromiter(range(10),dtype=int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
for i in gen:
    print(i,end=" ")

In [22]:
np.fromstring('1,2,3,4,5,6,6',sep=',',dtype=int)

array([1, 2, 3, 4, 5, 6, 6])

In [27]:
np.fromstring('12,34,45,2443e,2433,343',sep=',',dtype=complex)

C:\Users\niraj\AppData\Local\Temp\ipykernel_57536\439610838.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring('12,34,45,2443e,2433,343',sep=',',dtype=complex)


array([  12.+0.j,   34.+0.j,   45.+0.j, 2443.+0.j])

In [29]:
l=[12,23,432,454,454,567,754,22]
np.array(l)

array([ 12,  23, 432, 454, 454, 567, 754,  22])

In [3]:
import numpy as np
arr1=np.array([[1,2,3,4],[5,6,7,8],[12,13,14,15]])
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [12, 13, 14, 15]])

In [4]:
arr1.ndim

2

In [5]:
arr1.size

12

In [6]:
arr1.shape

(3, 4)

In [7]:
arr1.dtype

dtype('int32')

In [9]:
arr=np.array([1,2,3,4,5,6,7])
arr.ndim

1

In [10]:
arr.shape

(7,)

In [11]:
arr.size

7

In [25]:
arr2=np.array([[[1,2,3,4],[4,5,6,7]],[[11,12,13,14],[15,16,17,18]]])
arr2

array([[[ 1,  2,  3,  4],
        [ 4,  5,  6,  7]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18]]])

In [26]:
arr2.ndim

3

In [23]:
arr2.shape

(2, 2, 4)

In [24]:
arr2.size

16

In [28]:
arr2[0][0][1:]

array([2, 3, 4])

In [29]:
arr4=np.array([[[[1,2,3,4],[4,5,6,7]],[[11,12,13,14],[15,16,17,18]]]])
arr4

array([[[[ 1,  2,  3,  4],
         [ 4,  5,  6,  7]],

        [[11, 12, 13, 14],
         [15, 16, 17, 18]]]])

In [30]:
arr4.ndim

4

In [31]:
arr4.shape

(1, 2, 2, 4)

In [32]:
range(10)

range(0, 10)

In [35]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [39]:
np.arange(6.6,9,0.3)  #its accepting the upper bound(sue to the floaring no)

array([6.6, 6.9, 7.2, 7.5, 7.8, 8.1, 8.4, 8.7, 9. ])

In [40]:
np.arange(1,10)# it neglect the upper bound ( int stype)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [42]:
np.linspace(1,2,20)

array([1.        , 1.05263158, 1.10526316, 1.15789474, 1.21052632,
       1.26315789, 1.31578947, 1.36842105, 1.42105263, 1.47368421,
       1.52631579, 1.57894737, 1.63157895, 1.68421053, 1.73684211,
       1.78947368, 1.84210526, 1.89473684, 1.94736842, 2.        ])

In [44]:
np.linspace(1,1.25,70)

array([1.        , 1.00362319, 1.00724638, 1.01086957, 1.01449275,
       1.01811594, 1.02173913, 1.02536232, 1.02898551, 1.0326087 ,
       1.03623188, 1.03985507, 1.04347826, 1.04710145, 1.05072464,
       1.05434783, 1.05797101, 1.0615942 , 1.06521739, 1.06884058,
       1.07246377, 1.07608696, 1.07971014, 1.08333333, 1.08695652,
       1.09057971, 1.0942029 , 1.09782609, 1.10144928, 1.10507246,
       1.10869565, 1.11231884, 1.11594203, 1.11956522, 1.12318841,
       1.12681159, 1.13043478, 1.13405797, 1.13768116, 1.14130435,
       1.14492754, 1.14855072, 1.15217391, 1.1557971 , 1.15942029,
       1.16304348, 1.16666667, 1.17028986, 1.17391304, 1.17753623,
       1.18115942, 1.18478261, 1.1884058 , 1.19202899, 1.19565217,
       1.19927536, 1.20289855, 1.20652174, 1.21014493, 1.21376812,
       1.2173913 , 1.22101449, 1.22463768, 1.22826087, 1.23188406,
       1.23550725, 1.23913043, 1.24275362, 1.24637681, 1.25      ])

In [46]:
np.linspace(1,90,78)

array([ 1.        ,  2.15584416,  3.31168831,  4.46753247,  5.62337662,
        6.77922078,  7.93506494,  9.09090909, 10.24675325, 11.4025974 ,
       12.55844156, 13.71428571, 14.87012987, 16.02597403, 17.18181818,
       18.33766234, 19.49350649, 20.64935065, 21.80519481, 22.96103896,
       24.11688312, 25.27272727, 26.42857143, 27.58441558, 28.74025974,
       29.8961039 , 31.05194805, 32.20779221, 33.36363636, 34.51948052,
       35.67532468, 36.83116883, 37.98701299, 39.14285714, 40.2987013 ,
       41.45454545, 42.61038961, 43.76623377, 44.92207792, 46.07792208,
       47.23376623, 48.38961039, 49.54545455, 50.7012987 , 51.85714286,
       53.01298701, 54.16883117, 55.32467532, 56.48051948, 57.63636364,
       58.79220779, 59.94805195, 61.1038961 , 62.25974026, 63.41558442,
       64.57142857, 65.72727273, 66.88311688, 68.03896104, 69.19480519,
       70.35064935, 71.50649351, 72.66233766, 73.81818182, 74.97402597,
       76.12987013, 77.28571429, 78.44155844, 79.5974026 , 80.75

In [47]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [49]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [50]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [51]:
np.ones((2,2,3,4))

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]])

In [52]:
np.ones((2,2,3,4))+5

array([[[[6., 6., 6., 6.],
         [6., 6., 6., 6.],
         [6., 6., 6., 6.]],

        [[6., 6., 6., 6.],
         [6., 6., 6., 6.],
         [6., 6., 6., 6.]]],


       [[[6., 6., 6., 6.],
         [6., 6., 6., 6.],
         [6., 6., 6., 6.]],

        [[6., 6., 6., 6.],
         [6., 6., 6., 6.],
         [6., 6., 6., 6.]]]])

In [53]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [56]:
np.empty((3,5))

array([[0.000000e+000, 0.000000e+000, 0.000000e+000, 0.000000e+000,
        0.000000e+000],
       [0.000000e+000, 0.000000e+000, 0.000000e+000, 0.000000e+000,
        0.000000e+000],
       [0.000000e+000, 0.000000e+000, 0.000000e+000, 0.000000e+000,
        3.496989e-317]])

In [58]:
np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [59]:
np.linspace(2,4,4)

array([2.        , 2.66666667, 3.33333333, 4.        ])

In [61]:
np.linspace(2,4,4,endpoint=False)

array([2. , 2.5, 3. , 3.5])

In [64]:
np.linspace(2,4,4,endpoint=False,axis=0)

array([2. , 2.5, 3. , 3.5])

In [70]:
np.linspace([1,6],4,endpoint=False,axis=0)

array([[1.  , 6.  ],
       [1.06, 5.96],
       [1.12, 5.92],
       [1.18, 5.88],
       [1.24, 5.84],
       [1.3 , 5.8 ],
       [1.36, 5.76],
       [1.42, 5.72],
       [1.48, 5.68],
       [1.54, 5.64],
       [1.6 , 5.6 ],
       [1.66, 5.56],
       [1.72, 5.52],
       [1.78, 5.48],
       [1.84, 5.44],
       [1.9 , 5.4 ],
       [1.96, 5.36],
       [2.02, 5.32],
       [2.08, 5.28],
       [2.14, 5.24],
       [2.2 , 5.2 ],
       [2.26, 5.16],
       [2.32, 5.12],
       [2.38, 5.08],
       [2.44, 5.04],
       [2.5 , 5.  ],
       [2.56, 4.96],
       [2.62, 4.92],
       [2.68, 4.88],
       [2.74, 4.84],
       [2.8 , 4.8 ],
       [2.86, 4.76],
       [2.92, 4.72],
       [2.98, 4.68],
       [3.04, 4.64],
       [3.1 , 4.6 ],
       [3.16, 4.56],
       [3.22, 4.52],
       [3.28, 4.48],
       [3.34, 4.44],
       [3.4 , 4.4 ],
       [3.46, 4.36],
       [3.52, 4.32],
       [3.58, 4.28],
       [3.64, 4.24],
       [3.7 , 4.2 ],
       [3.76, 4.16],
       [3.82,

In [67]:
np.linspace([1,6],4,endpoint=False,axis=1)#transposes the matrix when axis =1

array([[1.  , 1.06, 1.12, 1.18, 1.24, 1.3 , 1.36, 1.42, 1.48, 1.54, 1.6 ,
        1.66, 1.72, 1.78, 1.84, 1.9 , 1.96, 2.02, 2.08, 2.14, 2.2 , 2.26,
        2.32, 2.38, 2.44, 2.5 , 2.56, 2.62, 2.68, 2.74, 2.8 , 2.86, 2.92,
        2.98, 3.04, 3.1 , 3.16, 3.22, 3.28, 3.34, 3.4 , 3.46, 3.52, 3.58,
        3.64, 3.7 , 3.76, 3.82, 3.88, 3.94],
       [6.  , 5.96, 5.92, 5.88, 5.84, 5.8 , 5.76, 5.72, 5.68, 5.64, 5.6 ,
        5.56, 5.52, 5.48, 5.44, 5.4 , 5.36, 5.32, 5.28, 5.24, 5.2 , 5.16,
        5.12, 5.08, 5.04, 5.  , 4.96, 4.92, 4.88, 4.84, 4.8 , 4.76, 4.72,
        4.68, 4.64, 4.6 , 4.56, 4.52, 4.48, 4.44, 4.4 , 4.36, 4.32, 4.28,
        4.24, 4.2 , 4.16, 4.12, 4.08, 4.04]])

In [68]:
np.logspace(2,3,5)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [72]:
np.logspace([2,5],3,axis=0)

array([[   100.        , 100000.        ],
       [   104.81131342,  91029.81779915],
       [   109.8541142 ,  82864.27728547],
       [   115.13953993,  75431.20063355],
       [   120.67926406,  68664.88450043],
       [   126.48552169,  62505.51925274],
       [   132.57113656,  56898.66029018],
       [   138.94954944,  51794.74679231],
       [   145.63484775,  47148.66363457],
       [   152.64179672,  42919.34260129],
       [   159.98587196,  39069.39937055],
       [   167.68329368,  35564.80306223],
       [   175.75106249,  32374.57542818],
       [   184.20699693,  29470.51702552],
       [   193.06977289,  26826.9579528 ],
       [   202.35896477,  24420.53094549],
       [   212.09508879,  22229.96482526],
       [   222.29964825,  20235.89647725],
       [   232.99518105,  18420.69969327],
       [   244.20530945,  16768.32936811],
       [   255.95479227,  15264.17967175],
       [   268.26957953,  13894.95494373],
       [   281.1768698 ,  12648.55216855],
       [   

In [76]:
np.logspace([1,2],[3],axis=0)

array([[  10.        ,  100.        ],
       [  10.98541142,  104.81131342],
       [  12.06792641,  109.8541142 ],
       [  13.25711366,  115.13953993],
       [  14.56348478,  120.67926406],
       [  15.9985872 ,  126.48552169],
       [  17.57510625,  132.57113656],
       [  19.30697729,  138.94954944],
       [  21.20950888,  145.63484775],
       [  23.29951811,  152.64179672],
       [  25.59547923,  159.98587196],
       [  28.11768698,  167.68329368],
       [  30.88843596,  175.75106249],
       [  33.93221772,  184.20699693],
       [  37.2759372 ,  193.06977289],
       [  40.94915062,  202.35896477],
       [  44.98432669,  212.09508879],
       [  49.41713361,  222.29964825],
       [  54.28675439,  232.99518105],
       [  59.63623317,  244.20530945],
       [  65.51285569,  255.95479227],
       [  71.9685673 ,  268.26957953],
       [  79.06043211,  281.1768698 ],
       [  86.85113738,  294.70517026],
       [  95.40954763,  308.88435965],
       [ 104.81131342,  3

In [78]:
d=np.linspace(4,7,100)
d

array([4.        , 4.03030303, 4.06060606, 4.09090909, 4.12121212,
       4.15151515, 4.18181818, 4.21212121, 4.24242424, 4.27272727,
       4.3030303 , 4.33333333, 4.36363636, 4.39393939, 4.42424242,
       4.45454545, 4.48484848, 4.51515152, 4.54545455, 4.57575758,
       4.60606061, 4.63636364, 4.66666667, 4.6969697 , 4.72727273,
       4.75757576, 4.78787879, 4.81818182, 4.84848485, 4.87878788,
       4.90909091, 4.93939394, 4.96969697, 5.        , 5.03030303,
       5.06060606, 5.09090909, 5.12121212, 5.15151515, 5.18181818,
       5.21212121, 5.24242424, 5.27272727, 5.3030303 , 5.33333333,
       5.36363636, 5.39393939, 5.42424242, 5.45454545, 5.48484848,
       5.51515152, 5.54545455, 5.57575758, 5.60606061, 5.63636364,
       5.66666667, 5.6969697 , 5.72727273, 5.75757576, 5.78787879,
       5.81818182, 5.84848485, 5.87878788, 5.90909091, 5.93939394,
       5.96969697, 6.        , 6.03030303, 6.06060606, 6.09090909,
       6.12121212, 6.15151515, 6.18181818, 6.21212121, 6.24242

In [81]:
d.ndim

1

In [82]:
d.shape

(100,)

In [83]:
d.reshape(25,4)

array([[4.        , 4.03030303, 4.06060606, 4.09090909],
       [4.12121212, 4.15151515, 4.18181818, 4.21212121],
       [4.24242424, 4.27272727, 4.3030303 , 4.33333333],
       [4.36363636, 4.39393939, 4.42424242, 4.45454545],
       [4.48484848, 4.51515152, 4.54545455, 4.57575758],
       [4.60606061, 4.63636364, 4.66666667, 4.6969697 ],
       [4.72727273, 4.75757576, 4.78787879, 4.81818182],
       [4.84848485, 4.87878788, 4.90909091, 4.93939394],
       [4.96969697, 5.        , 5.03030303, 5.06060606],
       [5.09090909, 5.12121212, 5.15151515, 5.18181818],
       [5.21212121, 5.24242424, 5.27272727, 5.3030303 ],
       [5.33333333, 5.36363636, 5.39393939, 5.42424242],
       [5.45454545, 5.48484848, 5.51515152, 5.54545455],
       [5.57575758, 5.60606061, 5.63636364, 5.66666667],
       [5.6969697 , 5.72727273, 5.75757576, 5.78787879],
       [5.81818182, 5.84848485, 5.87878788, 5.90909091],
       [5.93939394, 5.96969697, 6.        , 6.03030303],
       [6.06060606, 6.09090909,

In [85]:
d.reshape(5,20)

array([[4.        , 4.03030303, 4.06060606, 4.09090909, 4.12121212,
        4.15151515, 4.18181818, 4.21212121, 4.24242424, 4.27272727,
        4.3030303 , 4.33333333, 4.36363636, 4.39393939, 4.42424242,
        4.45454545, 4.48484848, 4.51515152, 4.54545455, 4.57575758],
       [4.60606061, 4.63636364, 4.66666667, 4.6969697 , 4.72727273,
        4.75757576, 4.78787879, 4.81818182, 4.84848485, 4.87878788,
        4.90909091, 4.93939394, 4.96969697, 5.        , 5.03030303,
        5.06060606, 5.09090909, 5.12121212, 5.15151515, 5.18181818],
       [5.21212121, 5.24242424, 5.27272727, 5.3030303 , 5.33333333,
        5.36363636, 5.39393939, 5.42424242, 5.45454545, 5.48484848,
        5.51515152, 5.54545455, 5.57575758, 5.60606061, 5.63636364,
        5.66666667, 5.6969697 , 5.72727273, 5.75757576, 5.78787879],
       [5.81818182, 5.84848485, 5.87878788, 5.90909091, 5.93939394,
        5.96969697, 6.        , 6.03030303, 6.06060606, 6.09090909,
        6.12121212, 6.15151515, 6.18181818, 6

In [86]:
d.reshape(2,5,10)

array([[[4.        , 4.03030303, 4.06060606, 4.09090909, 4.12121212,
         4.15151515, 4.18181818, 4.21212121, 4.24242424, 4.27272727],
        [4.3030303 , 4.33333333, 4.36363636, 4.39393939, 4.42424242,
         4.45454545, 4.48484848, 4.51515152, 4.54545455, 4.57575758],
        [4.60606061, 4.63636364, 4.66666667, 4.6969697 , 4.72727273,
         4.75757576, 4.78787879, 4.81818182, 4.84848485, 4.87878788],
        [4.90909091, 4.93939394, 4.96969697, 5.        , 5.03030303,
         5.06060606, 5.09090909, 5.12121212, 5.15151515, 5.18181818],
        [5.21212121, 5.24242424, 5.27272727, 5.3030303 , 5.33333333,
         5.36363636, 5.39393939, 5.42424242, 5.45454545, 5.48484848]],

       [[5.51515152, 5.54545455, 5.57575758, 5.60606061, 5.63636364,
         5.66666667, 5.6969697 , 5.72727273, 5.75757576, 5.78787879],
        [5.81818182, 5.84848485, 5.87878788, 5.90909091, 5.93939394,
         5.96969697, 6.        , 6.03030303, 6.06060606, 6.09090909],
        [6.12121212, 6.15

In [89]:
np.random.rand(3)#uniform   distribution   

array([0.69667876, 0.27833991, 0.83137691])

In [90]:
np.random.randn(5) #standard normal distribution

array([ 1.67293949, -0.09824472,  0.70926385,  0.72222037, -0.57940498])

In [91]:
np.random.randn(5,4)

array([[-1.23536893, -0.25946319,  0.80023386,  1.98838729],
       [ 0.7057637 , -1.04684721, -1.66590208,  0.28594059],
       [-0.85074104,  0.24576816, -1.02807003, -0.86344717],
       [ 2.14560812, -1.30870205, -0.14487634, -0.64111659],
       [-0.17190515,  0.88512213, -0.47954906, -0.05786323]])

In [98]:
np.random.randint(5,60)

5

In [4]:
import numpy as np
arr=np.random.randint(10,100,(4,5))
arr

array([[14, 29, 45, 97, 28],
       [27, 68, 75, 62, 80],
       [11, 51, 34, 24, 83],
       [71, 69, 21, 60, 84]])

In [5]:
np.random.randint(10,100,(4,5)).reshape(10,2)

array([[93, 99],
       [84, 70],
       [11, 90],
       [84, 83],
       [26, 13],
       [26, 79],
       [30, 58],
       [75, 75],
       [79, 73],
       [41, 25]])

In [6]:
arr.reshape(2,5,2)

array([[[14, 29],
        [45, 97],
        [28, 27],
        [68, 75],
        [62, 80]],

       [[11, 51],
        [34, 24],
        [83, 71],
        [69, 21],
        [60, 84]]])

In [7]:
arr.reshape(5,-1)#if we gin any negative no it gives an output as factor f this no

array([[14, 29, 45, 97],
       [28, 27, 68, 75],
       [62, 80, 11, 51],
       [34, 24, 83, 71],
       [69, 21, 60, 84]])

In [8]:
arr.max()

97

In [9]:
arr.min()

11

In [22]:
arr

array([[14, 29, 45, 97, 28],
       [27, 68, 75, 62, 80],
       [11, 51, 34, 24, 83],
       [71, 69, 21, 60, 84]])

In [21]:
arr[2:,3:]#row:,column:

array([[24, 83],
       [60, 84]])

In [25]:
arr[:,2:3]

array([[45],
       [75],
       [34],
       [21]])

In [27]:
arr[:,(2,4)]

array([[45, 28],
       [75, 80],
       [34, 83],
       [21, 84]])

In [31]:
arr>10

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [30]:
arr[arr>10]

array([14, 29, 45, 97, 28, 27, 68, 75, 62, 80, 11, 51, 34, 24, 83, 71, 69,
       21, 60, 84])

In [32]:
sorted(arr[arr>10])

[11,
 14,
 21,
 24,
 27,
 28,
 29,
 34,
 45,
 51,
 60,
 62,
 68,
 69,
 71,
 75,
 80,
 83,
 84,
 97]

In [33]:
arr

array([[14, 29, 45, 97, 28],
       [27, 68, 75, 62, 80],
       [11, 51, 34, 24, 83],
       [71, 69, 21, 60, 84]])

In [35]:
arr1=np.random.randint(2,4,(3,3))
arr1

array([[2, 2, 3],
       [2, 3, 2],
       [2, 2, 2]])

In [36]:
arr2=np.random.randint(2,4,(3,3))
arr2

array([[2, 2, 2],
       [3, 2, 3],
       [3, 2, 3]])

In [37]:
arr1*arr2#multiplying by index by index

array([[4, 4, 6],
       [6, 6, 6],
       [6, 4, 6]])

In [39]:
np.multiply(arr1,arr2)

array([[4, 4, 6],
       [6, 6, 6],
       [6, 4, 6]])

Matrix Multiplication

In [40]:
arr1@arr2

array([[19, 14, 19],
       [19, 14, 19],
       [16, 12, 16]])

In [41]:
arr2**2

array([[4, 4, 4],
       [9, 4, 9],
       [9, 4, 9]])

Array Broadcasting

In [45]:
arr=np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [49]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [50]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [52]:
b=np.array([5,6,7])

In [55]:
c=b.reshape(3,1)
c

array([[5],
       [6],
       [7]])

In [56]:
arr+c

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [63]:
b=np.array([[5,6,7]])
b

array([[5, 6, 7]])

In [64]:
b.T

array([[5],
       [6],
       [7]])

In [67]:
arr=np.random.rand(5,4)
arr

array([[0.4339728 , 0.53822496, 0.65269394, 0.08086075],
       [0.56060546, 0.72511828, 0.40923266, 0.6061491 ],
       [0.2846855 , 0.28823236, 0.59648482, 0.40371801],
       [0.69377637, 0.31955043, 0.24973028, 0.4432745 ],
       [0.36523814, 0.11250219, 0.59721677, 0.73113591]])

In [68]:
np.sqrt(arr)

array([[0.65876612, 0.73363816, 0.80789476, 0.28436025],
       [0.74873591, 0.85153877, 0.63971295, 0.77855578],
       [0.53355928, 0.53687276, 0.77232429, 0.63538808],
       [0.83293239, 0.56528792, 0.4997302 , 0.66578863],
       [0.60434935, 0.33541347, 0.77279802, 0.85506486]])

In [69]:
np.exp(arr)

array([[1.54337689, 1.71296358, 1.92070815, 1.08421991],
       [1.75173278, 2.06497534, 1.50566198, 1.83335772],
       [1.32934389, 1.33406725, 1.81572496, 1.49738164],
       [2.00125878, 1.37650879, 1.28367913, 1.55779989],
       [1.44085709, 1.11907471, 1.81705448, 2.07743905]])

In [70]:
np.log10(arr)

array([[-0.36253749, -0.26903617, -0.18529042, -1.09226222],
       [-0.25134268, -0.13959115, -0.38802972, -0.21742053],
       [-0.54563465, -0.54025727, -0.22440061, -0.39392188],
       [-0.1587805 , -0.49546059, -0.6025288 , -0.35332725],
       [-0.43742388, -0.94883901, -0.223868  , -0.13600188]])

In [73]:
arr1=np.random.randint(2,5,(5,5))
arr1

array([[2, 2, 2, 2, 4],
       [4, 4, 2, 4, 4],
       [3, 4, 4, 3, 3],
       [3, 2, 3, 4, 3],
       [4, 3, 4, 3, 4]])

In [74]:
np.log10(arr1)

array([[0.30103   , 0.30103   , 0.30103   , 0.30103   , 0.60205999],
       [0.60205999, 0.60205999, 0.30103   , 0.60205999, 0.60205999],
       [0.47712125, 0.60205999, 0.60205999, 0.47712125, 0.47712125],
       [0.47712125, 0.30103   , 0.47712125, 0.60205999, 0.47712125],
       [0.60205999, 0.47712125, 0.60205999, 0.47712125, 0.60205999]])

In [107]:
np.random.seed(30)
np.random.rand(2,4)

array([[0.64414354, 0.38074849, 0.66304791, 0.16365073],
       [0.96260781, 0.34666184, 0.99175099, 0.2350579 ]])